projectName: tictactoe
apiVersion: v0.0.0
author: TBD.
licence: TBD.
serviceUrlPrefix: /rest
servicePort: 3007
baseUrl: "http://localhost:3007/rest"
servicesRoot: services
services: 
    - /monitoring/isAlive
    - /games
loginCredentials: 
    user: username
    pass: password
